### ISSUE TITLE
nx500 boot process

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#13]
Otto, did you know that the camera, if turned off but without battery being pulled, actually hibernates?
Upon wakeup the memory remains patched - I tested it.
Only if the battery is pulled will the camera do a resume from somewher else (I guess from the zswap)
Can you check too on your camera?

I also looked a bit into /sys/power/bootmode:
it is 3 after a warm boot (no battery pull) and 2 after a cold boot (battery pull)

I think the BT script might be tuned as follows: 
1. have it check whether a key is pressed when it is executed or if warm boot. If yes, skip sdcard execution.
2. else launch the sdcard script.

The issue is that BT is activated very late during resume process :-(

look at this: [root@nx500 ~]# cat /usr/bin/hibernation.sh        
#!/bin/sh

bootmode="`cat /sys/power/bootmode`"
if [ $bootmode -eq 4 ]; then
        echo -e "\nbootshell set to cold-boot... \n"    
        /bin/touch /tmp/.hib_ready      
        exit

I wonder whether the bootmode is actually the one that tells the camera from where to resume.

Thoughts?

**Comment by ottokiksmaler** [comment]
Here's the thing - I'm not quite sure what they were doing, because:
1. They use both zram and zswap - you don't normally do that
2. They use hybrid-sleep - it puts system to suspend **and** hybernates it in the background (I use it on my laptop - if everything is OK it wakes up instantly, if I lose power during sleep it recovers from hybernation) - but they don't update hybernation image - ever.
3. If they resume from disk they restore camera state from pref partition (if from RAM it's already there - no need to restore anything)

My guess (just a guess) is that they needed a way to automate sleep that would also recover gracefully from power loss (removal/depletion of the battery) so they just went the easy way - use hybrid-sleep but don't update contents of swap file.
Regarding the /usr/bin/hibernation.sh file (and many others present in the filesystem that are normally used in linux boot/wakeup) - there is not guarantee at all that they are being executed ever (or have been ever) - there are so many "leftovers" in the fs that it's quite possible they don't do anything or they trash everything (though I don't thik this one does any trashing).
Regarding hacking whatever script file, here's my procedure:
1. Any first modification calls (fork with &) another script file placed in rootfs that has sleep 120 at the beginning
2. This gives me ample time to either connect via telnet or, the worst case scenario, reflash the firmware (yes it slowes me down, but that's livable).
3. First thing I check in script is what filesystems are there
4. If it can already see SD card -> execute from SD card if file exists, fail gracefuly otherwise

Regarding cold boot - I doubt it updates the swap file (at least it will not on it's own - you can always just pull the battery instead of normal power-off that triggers sleep).

Hope this helps :)

Another thing, there seems to be full support for SDB (Samsung/Tizen version of Android's ADB) over USB (though only in factory mode). 

So many things, so little time...

**Comment by gitvasile** [comment]
Let us also not forget that there's full system console available with proper USB cable...

**Comment by gitvasile** [comment]
not a bad idea to sleep 120 sec.
I think you are right about not updating the zswap  but what I do not understand is that it seems to write something...

**Comment by gitvasile** [comment]
btw I sent you a PM on eoshd.

**Comment by ge0rg** [comment]
Hey folks, I'm also very interested in having a complete documentation of the boot process. Maybe it would be great to write up everything we know (how it boots, partition layout, 1st and 2nd stage bootloaders, ...) into a wiki/markdown file?

**Comment by gitvasile** [comment]
/usr/bin/change-booting-mode.sh

is this redoing the fast boot image (i.e. the one restored on cold boot?)

**Comment by ottokiksmaler** [comment]
Don't know, but last night I did boot to recovery (via systemd target recovery) and it fully boots, taking longer time, checking filesystem (as it was changed a long time ago in factory) and di-camera-app has pid 249 (usually 247). I did not perform regular shutdown but popped out the battery when I was finished, as I didn't want to update the hibernation image (not sure it would do it anyway, but just to be sure). 
So, I guess this is one possible way to experiment with the system without the fear of damaging functionality (battery pop out and we're back to hibernated image).

**Comment by gitvasile** [comment]
> Don't know, but last night I did boot to recovery (via systemd target recovery) and it fully boots, taking longer time, checking filesystem (as it was changed a long time ago in factory) and di-camera-app has pid 249 (usually 247)
well, by doing systemctl start recovery-mode and then systemctl reboot, the camera takes a long time to **shut down**, not to boot :-( so this is not recovery, it is something else.

**Comment by gitvasile** [comment]
`
cat etc/parttab 
# nx500 partition table
# <vol>       <dev>       <size(M)>        <image>  <order> <compress>  <fs>  <mkfs-option>  <mount-point>
#
adj           /dev/mmcblk0p1     20             none   1    None        raw
rtos          /dev/mmcblk0p7     30          rom.bin   2    None        raw
rtos_data     /dev/mmcblk0p8     50             none   3    None        raw
#extended     /dev/mmcblk0p4      0             none   4    None        raw
platform      /dev/mmcblk0p10  1024       rootfs.img   5    LZO        ext4
opt           /dev/mmcblk0p11   100          opt.img   6    LZO        ext4      -j              /opt
pref          /dev/mmcblk0p2     10             none   7    None        raw
pref_default  /dev/mmcblk0p3     30 pref_default.bin   8    None        raw
pref_recovery /dev/mmcblk0p5     20             none   9    None        raw
opt-usr       /dev/mmcblk0p14     0             none  10    None       ext4      -j              /opt/usr
rImage        /dev/mmcblk0p13    10           rImage  11    None        raw
pcache        /dev/mmcblk0p12     5      pcache.list  12    None        raw
devicem4      /dev/mmcblk0boot1   4     devicem4.bin  13    None        raw
snapshot      /dev/mmcblk0p9    100     snapshot.img  14    LZO         raw
uImage        /dev/mmcblk0p6     10           uImage  15    None        raw
bootloader    /dev/mmcblk0boot0   4   bootloader.bin  16    None        raw
`

**Comment by gitvasile** [comment]
@ottokiksmaler ok recovery mode does not work for me, when you get to your PC could you send me the systemctl command you used? thx

**Comment by ottokiksmaler** [comment]
Will do. I first have to remember it :(

**Comment by gitvasile** [comment]
I am very sure `systemctl start recovery-mode` followed by `systemctl reboot` still does not reboot - the cam simply wakes from hibernate image.
