### ISSUE TITLE
Auto start mods from keyscan 

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#17]
I think we need a clearly documented method of auto executing scripts in two ways 
1. Scripts that need executing only after power cycle (they survive sleep) 
2. Scripts that need executing even without power cycle (like rolling shutter) 
Method should also work with scripts on SD card and ones on camera filesystem. 
Right now I am leaning towards having directory auto in scripts directory (and another one for sleep). Contents would be controlled by GUI application via a series of checkboxes (or manually). 
Also, I will have to find a solution for everything working on camera, on SD card and in factory mode. 
Any thoughts?

**Comment by gitvasile** [comment]
I would start with finalizing the hook that:
1. runs "always on" scripts from opt
2. if power cycle runs "on power cycle" scripts from opt
3. If there are "always on" or "power cycle" scripts on sdcard, runs them (instead of these from opt)

I also noticed that there are some functions in di-camera-app that suggest exit from factory mode might also be triggered manually (i.e. not through pulling the sd card) - a clean exit would be nice rather than the force kill of dfmsd which does not really exit factory mode.
