### ISSUE TITLE
dangerous tests - plans

### ISSUE THREAD

**Issue by gitvasile** [ottokiksmaler/nx500_nx1_modding#22]
Otto, FYI I opened a gofundme campaign for a NX500. If it succeeds and I can get a burner camera I will do some tests that I do not dare do right now.

I will start with messing with the hibernation image - if I manage to tweak it I we will be able to get rid of the bluetooth mod and your keyscan will be instantly available upon camera resume.

If you have other ideas, let us make a list here.

**Comment by ottokiksmaler** [comment]
First test I would do is to go to recovery (as I did, via systemd) and see if that really goes through all the real files in the filesystem and whether it can update the hibernation image. That way you could test relatively harmlessly if something is working and if it is, then power the camera off or suspend it to disk (so it updates the hibernation image) and pop the battery out if something is wrong so the hibernation image stays the same.
 
Second thing would be to see how the camera reacts to invalid rtos and rtos data partitions - of it's possible to reflash firmware or if it's gone for good. If it survives invalid rtos we could experiment with it. 

Best of luck :)

**Comment by gitvasile** [comment]
Going to take a while though - the campaign just started. But yep, will do, if I can get the camera.

**Comment by ottokiksmaler** [comment]
When  the keyscan is running from opt and scripts are on opt as well it resumes in well under a second (as it's not killed at all).

**Comment by gitvasile** [comment]
yep I know :-) that is how it works for me.
What I want to do is to make it happen for **cold resume** too.

**Comment by KinoSeed** [comment]
playing with that Bluetooth I though was harmless, until my only way was reinstalling the firmware.
(and that was still with ro / )
and in the end couldn't figure out how to "turn the switch" for BT. 

Otto, how "safe" is it to install the keyscan in opt?
(should I bundle that option in? )

**Comment by gitvasile** [comment]
@KinoSeed you saw my opinion on eoshd: http://www.eoshd.com/comments/topic/19099-petition-for-samsung-nx1-hack/?do=findComment&comment=144579

**Comment by KinoSeed** [comment]
@gitvasile ?

**Comment by gitvasile** [comment]
I meant my opinion about storing mods on /opt

**Comment by ottokiksmaler** [comment]
I have been running everything from /opt/usr/devel/scripts for a long time now a and have seen no problems at all. Keyscan is up and running "instantly", as well are all the auto run scripts, after wakeup (warm).

**Comment by Tommixoft** [comment]
@KinoSeed  `playing with that Bluetooth I though was harmless, until my only way was reinstalling the firmware.`

what's happened?

**Comment by KinoSeed** [comment]
it killed the WiFi too
after "reset" and reload of the backup setting, it showed up as trying to connect, but it was never able to work properly (would not connect). Only firmware flash solved the problem.

**Comment by gitvasile** [comment]
@ottokiksmaler so how did you go into recovery? what was your exact command? thx

**Comment by bortek** [comment]
Just re-iterating the question, how does one goes into a recovery mode?

**Comment by vasile-gh** [comment]
I could not find a way. Had two bricked cameras and sent them to Samsung.

Kind regards

**Comment by bortek** [comment]
It's a pity because this is a damm good peace of equipment. Do you think Samsung can still take them in for a re-flashing ? :) 

Anyway I am still not sure how could I have bricked it. What I did new this time was to add new resolution to /etc/X11/xorg.conf.d/display.conf and undet the Monitor secction added new Modeline.

The camera starts, the display backlight is on, the lens initializes and moves in-out, status led is blinking approx 1 sec. But the startup is never completed. So it is not completely dead in that sense. 

I might have forgotten forgotten to do sync filesystem and remount to read-only before doing "systemctl rescue". Could this be more likely cause of it?

Wonder if there is a way to hook up a motherboard directly to a PC via serial or some other means, but then I would need a way to talk to it.

**Comment by vasile-gh** [comment]
Your could always ask them.

I would do this before disassembling the camera.

I am fairly sure there are some pins which give access to the console but
Samsumg was very secretive, we could not get any technical manuals...

**Comment by bortek** [comment]
I have already opened the camera couple of times and I doubt those engineers who can fix it are still around there. Anyway I should probably setup a notification for a "nx500 for parts" item on ebay and put out the camera in the drawer. Well well, it was fun and learning journey anyway :-/  Thanks for your reponse!

**Comment by ottokiksmaler** [comment]
There is a procedure in the service manual. It requires shorting two pins on the board and, unfortunately, a .BIN file for recovery. So, it's not "hardware" bricked and could be relatively simple to recover, but we have been unable to locate the recovery file.

**Comment by bortek** [comment]
Hi Otto. Well that's something. Do you mind to share which pins are those, or the service manual. Searched for it but couldn't find one.

Is it not a latest firmware bin file but some other one?

**Comment by ottokiksmaler** [comment]
Please confirm that you have received a mail.

**Comment by bortek** [comment]
Thanks Otto. I received the manual :)

**Comment by bortek** [comment]
So now I only need to find  a downloader.bin somewhere on the internet :)  Perhaps the one from nx1 or nx300 will do if they use the same recovery code.

**Comment by ottokiksmaler** [comment]
If you manage to locate it, it would be a "game changer" for our community.

**Comment by bortek** [comment]
Hehe I will do my best. Perhaps it is "shipped" and baked into i-Launcher or some other tool. Will have to take a look. Of course I will report a progress if there will be some.

**Comment by Tommixoft** [comment]
Sorry to put in my 2 cents, but I doubt that there is any kind of
community. NX is dead. sony a6400 beats NX1. There is no lense for nx. I
had an NX500, I had NX1. Game changer was your hacks, not some recovery.
All im saying is NX is very old. No lenses. When I had nx1 I also was like
many of nx users - "oh it's the best camera", but it's not. It's like a
hammer without nails :)
Anyway you Otto, Vasile made it much better tool, sad it was very
restrictive on video, way too dark, no flat profile.

**Comment by vasile-gh** [comment]
Kind of agree, although I will use mine until they are dead.

**Comment by bortek** [comment]
Agree. Every camera has it's own area of use and as well as it's price and what you get for the money. But if you have one laying around and want to tinker with it then this is the right place. Community in this sense is very small but still a community ;)

**Comment by ttbek** [comment]
What is this hammer with no nails?  I have a hammer, so everything is a nail 😄 My 5DSR isn't fundamentally different, just a bigger hammer.  I'm a bit doubtful that this file has ever been available to end users.  I guess I would assume it is some version of firmware, but without knowing what was in it, it's hard to say if it's possible to build it or not.  By the way, why is the NX500 source not available?  Maybe just no one requested it?  

NX300 and NX300M sources I think have disappeared?  I still have them, well, at least the NX300 one, I would need to double check on the NX300M, so if someone needs them, pm I guess.  

NX1 is still available.  I think Samsung's build process changed quite drastically between NX300 and NX1.  Back in NX300 I think the build instructions used CodeSourcery etc... etc... and were quite complicated.  The NX1 ones don't look so bad, though the Tizen tools repo may be rather outdated (listed for Ubuntu 12.04).  

https://opensource.samsung.com/

Camera_SDK_OpenSource.zip  <-- This isn't the SDK people had to sign NDAs for right?  It's really small and the only stuff in it is some libexif and libjpeg stuff.  I think it's some phone camera thing as there are some Android related files but I'm not seeing Tizen in there.  

DNG converter is still available there, both 1.0 and 2.0 for Mac and Windows, not that those help at all with the problem at hand...  
Sorry for the big tangent.  

I think Otto says this file would be a game changer because it would allow us to be much more reckless in our mod attempts with far less fear of permanently losing what is becoming a rarer and rarer commodity.

**Comment by Tommixoft** [comment]
Just move on..you are spending your valuable time on dead camera. It's like
spending time reverse engineering canon 5D. :) Your camera costs 300 eur...
it's pocket change, compared to camera prices. It have 4k crop. shitty
colors in video (too dark, too saturated), full readout may lead to
overheating and so on. even if you would receive all info that's
possible-you still won't make it better there will always be some hardware
limitations. Just buy camera that does what you want and stop wasting your
life on the past :)
Just my 2 cents :D

**Comment by ttbek** [comment]
I don't need your 2 cents, I've got plenty of money and plenty of cameras.  Not sure which camera you're saying is 300 Euros, certainly not a 5D, which also doesn't shoot any video, so I'm not sure what you're on about 4k crop for.  The 5D is well under 300 Euro I would imagine and the NX1 is also not a 300 Euro camera yet.  You're here just to bad mouth the NX500 then?  There is no camera on the market that does what I want.  The Canon R5 is theoretically a step in the right direction for me, I probably will get one.  This isn't about penny pinching though, it's about reducing wastefulness and what I personally find interesting to do with my free time.  I do still get out my original 5D (apparently I need to specify original since you seem to use 5D for some other camera) from time to time.  I don't shoot video much either, so I don't get why you attack that.  It is fairly saturated, but it's really at quite a reasonable point for anyone shooting occasional clips that doesn't want to putz about with color grading.  

What I would really like is a genuinely good camera that is properly programmable.  You can get one or the other but not both.  Either you get a god awful sensor with a crappy lens that you can write ML algorithms for, or you get a nice camera which certainly takes very nice images but is all locked down and totally useless for tinkering and/or research.  Sure, strictly speaking there is sort of a 3rd option where you fork over absurd amounts of money to a vendor like Edmund's Scientific for essentially a custom built camera, but that is a bit of a stretch for even my ample budget.  Isn't that actually your 2nd two cents?  You can have all four back.

**Comment by Tommixoft** [comment]
300 is for nx500. My two cents is VERY valuable. Because you write like
anybody cares about NX system. But nobody does. Even if you mod that
camera, get a recovery image and so on -there would be like 3 people who
would be happy about that.
Tem me single thing that Nx500 or Nx1 doing better then for example 800
euro Fuji X-H1. Or cheaper, less professional cameras? Nothing. I had Nx1,
i had Nx500. i LOVED IT. but it's very limited even with fool root access.

**Comment by ottokiksmaler** [comment]
This is a github repo, not a forum. Please, take the off topic discussion somewhere else.
