### ISSUE TITLE
Focus stacking improvements 

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#29]
@ottokiksmaler
From dpreview.com 
- [x] A more or less serious bug. I've made several tests with 5 shots - 2 seconds (in case it matters). And the fifth picture is always front focused. It's like if you have divided in five segments (but six focus distances) instead of four segments (but five focus distances). Could you check it? - **BUG FIXED**
- [x] My very first suggestion: A "Focus stack in progress..." message would be really nice (and if you could add a counter with the taken picture...). - **FEATURE ADDED**
- [x] Could you make the focus stack parameters persistent? (I'm not so sure if I would make Near and Far positions persistent).  - **FEATURE ADDED**
- [x] I would also swap the "?" and "stack" buttons. More over I would rename "stack" to "start" or "go". I mean, we know we are inside the focus stack function, therefore a more assertive text would be more user friendly IMO. - **Buttons swapped and renamed: ?->Conf. Stack->Start**
- [x] As the stack process is somehow long and the "buttons" are somehow tiny, you can accidentally launch it without having set the focus distances (you wanted to press Far, but you touched Stack). If possible, I wouldn't allow launching all the process unless Far an Near are correctly set. - **BUG FIXED**
- [x] Another small bug. I haven't found the exact trigger, but the "Far/Near position set" text sometimes is kept on the screen persistently. (Maybe when you quickly touch other stack buttons?) - **BUG FIXED**
- [x] I've re-tested again and I'm nearly sure that what I had posted is the cause. The camera does actually takes five pictures and then, after taking the last picture, it actually does another extra focus movement which apparently reaches the Far position. It really seems a silly bug in the math... (I hope this is the case). - **BUG FIXED**
- [x] Is it normal that on the NX500 the AF jump to manual focus. My far point always is in the center, strange - **BUG FIXED**
- [x] Can I combine Focus Stack and Silent mode? - **YES** (on NX500)
- [ ] Suggestion: Is it possible to have an automated  video sequence where the camera take a video for 1 or 2 seconds where the focus starts from nearest to widest point (something similar to what Panasonic is doing). AF must be off in this video. The video length has to be in the range of the time the lens needs to drive from closest to the widest focus - **IN PROGRESS - Issues with crashing**

**Comment by outerbeat** [comment]
Using KS mod-pack v1.55
NX1 and Sandisk 95MB\s 

Focus pull (EV+halfshutter) doesn't work during the video properly, it give "sdcard is too slow" message and stop the record, but focus actually pulls, yes. I did lower bitrates, best one is 60 mbps for this function. Any higher bitrate and camera stops the shooting, but at 60 mbps it works fine.

I think it might be related to key-pressing because when I decrease bitrate from say 200 to 50 with 10-20 mbps steps, it also react little bit faster on key-pressing and gives error message faster and faster, but with decreasing bitrate this message appears later and later in other cases, when it's not about focus pull and EV button involved
