### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#31]
Feature requests - collected from dpreview and eoshd or directly on github. NB. These are **requests** not commitments nor promises and may well be unachievable.
- [ ] Disable that error message about high volumes may damage your hearing (Georg P. Mueller @ eoshd)
- [ ] 4K @ 60 p video recording mode (Vonzar @ dpreview)
- [ ] fix rare random drop frames while recording 100 or 120 frames (Vonzar @ dpreview)
- [ ] 10 bit internal recording (Vonzar @ dpreview)
- [ ] 5-pictures AEB for NX500
- [ ] make iFn button do useful work (vasile @ dpreview)
- [ ] programmatically (i.e. not via simulated keypress and without waking up screen) take picture (vasile @ dpreview)
- [ ] higher frame rates for the NX500 (Chopperguy @ eoshd)
- [ ] Q: Samsung Camera Manager App can be made to work with manual lenses for live view? CMCFirm @ eoshd
- [ ] move loupe on non-samsung MF lenses
- [ ] e-shutter at speeds lower than 1/15 sec
- [ ] true BBAF - see [this](http://www.dpreview.com/forums/post/57823270) - merged with kill the AF part of Half-Shutter (ARSPR @ dpreview) [note - see if memory patch is possible]
- [ ] [focus bracketing](http://www.dpreview.com/forums/post/57826810) (tecnoworld @ dpreview)
- [x] time-lapse to use full software suspend and timer wake-up (vasile @ dpreview) - done by Kino Seed AFAIK
- [ ] automatic recording restart after 70 min based on recording time (as a workaround to recording memory leak) RieGo @ eoshd
- [ ] multiple video setting profile slots with UI. ([MountaineerMan @ dpreview](http://www.dpreview.com/forums/post/57924341))
- [ ] "sticky" MF mode upon lens change [classicam@eoshd](http://www.eoshd.com/comments/topic/19099-petition-for-samsung-nx1-hack/?page=77#comment-150388)

**Comment by Vonzar** [comment]
NX1 features request. 
A) 4K @ 60 p video recording mode. 
B) Fix the bug with the rare random drop frames while recording 100 or 120 frames (reported by many users recording slow mo) 
C) 10 bit internal recording. 

Thank you very much !

**Comment by Chopperguy** [comment]
Hi Vasile, 
Well done on all your progress here. The Vasile, Otto, and Kino train is powering along.
Perhaps you would add higher frame rates for the NX500 onto the request list.
Its possible when you are exploring the burner cam, you might find some clues.
Many thanks,
Chopperguy

**Comment by TimShoebridge** [comment]
Hi Vasile, I have two requests if you would be so kind as to consider them. The first is a bug-fix so I have no idea how feasible it is. When you shoot video the NX1 will switch from MF to AF as soon as it detects that whatever you are shooting goes out of focus. For almost all serious video work we need to shoot in MF mode, the fact that the NX1 makes up its own mind to switch to AF is crazy. The second request is to do with noise reduction. Although a menu option was introduced with one of the firmware updates to allow control over noise reduction I am suspicious that you can not disable it fully. It would be really great to have more manual control over the amount of noise reduction that is applied in camera. This kind of facility would likely have more positive impact on image quality than bitrate can.

**Comment by WWilhelm** [comment]
@TimShoebridge,
Hi Tim,
About your second request...The Noise reduction filter does not apply when the camera switches to video mode. There is no NR on video mode...maybe there was some NR on earlyer firmware, I'm not sure, but since the FW 1.11 there is no NR for sure.
There is at least one reason why Samsung does not apply this filter to video mode. I'll try to explain.
This filter is avery processor "hungry" one, and since the increased Bitrate (the Pro mode) it is actually unnecesary. That means, it is allmost impossible to apply this filter in real time, when you have to deal with, let's say, at least FHD (1080p/24fps) and above without getting a really, really bad quality (ugly artifacts, blurring and so on) . That's the reason why Samsung did set the ISO limit in video mode to max 6400. This limit alows you to get a decent quality (some people can live with it, some people may not like the excesive grain, so they can use a denoising filter in postproduction...for that "noise" it's very easy to use such a filter and the results are unbelievable good when you try to get rid off it.
Actually the NR filter applies only in Photo mode but even here for 6400 ISO and above and for long time exposures as well.
If you still think that you may encounter some NR artifacts, just post some examples and we can discuss them...many "issues" have distinguished patterns, so it will be no problem to find out if your problems are based on a bad noise filter or maybe something else...
But, once again, in video mode there is no Noise Reduction filter.

Thanks,
Wilhelm

**Comment by WWilhelm** [comment]
Hi everybody, Otto and nea Vasile...and, nea Vasile thanks for inviting me to this, until now, small comunity but with obviously a big increasement potential.

The first thing I've noticed, is the picture profile...they gave me a cross and two dots !!!
Well, I can can live with the burden of carrying a cross (I'm not the first one), the two dots is something that concerns me: are these nails or wood sticks? Am I getting nailed or burned? :-))

I do also have some requests or better said wishes. And one trade. For NX500.

The first one will be the **focus peaking in UHD mode**...it's really some kind of a pain in the rear to focus on the relatively small Display and at the same time try to take a look at the entire scene in front of the camera and all around it. Why Samsung didn't implement this feature, is still a mistery for me, maybe they had their reasons, but I can't still figure it out what these reaseons may sould be.

The second one is, if possible, to apply the histogramm feature also in video preview mode. For me at least, this is one of the most important features when it comes to get the right exposure settings as fast and accurate as possible...

The trade...well, the trade will be between the "B" and a "T" exposure in photo mode.
Why? The "Bulb" exposure is limited to 30sec. but you have to stick with your finger (actually entire one hand) to the exposure button, while with a "Time" exposure, your hand is free.
There are lots of things you can do with a free hand...counting the finger from the other hand, for example, or rolling a joi...or, if you want to take some astrological pictures in the middle of the night, and the girlfriend or even worse, the wife, wakes up and asks "what the hell are you doing in the middle of the night?"...then you can simply show her the finger of your free hand. Or people you don't like. Or Samsung because it didn't put this feature on their settings at all.

Thanks,

Wilhelm

**Comment by ottokiksmaler** [comment]
For TIME shot - do you want to enter the number of seconds for exposure or have Bulb on / bulb off button?

**Comment by Fickert07** [comment]
Hi Vasile, I have a request in regards to getting live video out (hopefully standard av resolution) for fpv while using this on a drone. I am hoping there is some way to pull live video through the usb port, or even through the hdmi port (av or hd) without effecting the recording video resolution. Currently you cannot record any higher resolution that 1080p at 24fps while using live video out via the hdmi port. 

Thanks,

Dustin

**Comment by WWilhelm** [comment]
Hi Otto,
Boy, it looks like ordering a Steak: how do you want it, medium, rare? :-)
I'm an old fashioned guy so, Bulb on/off without a time limit will be just perfect.
If nea Vasile will put the request on the bottom of the list, so when the time comes just take a look at it, will be also great.

Thanks a lot,
Wilhelm

**Comment by TimShoebridge** [comment]
Hi Wilhelm, Thanks a lot for your reply to my post. Really appreciated. I took a guess that the problem I am seeing is an NR problem because it tends to occur in darker areas of a scene, especially low light situations. In good light the NX1 performs fantastically. 

Not sure if I can successfully attach a screenshot but if so then please take a look. This is a screenshot of a video at 100% resolution. The girl's face is almost totally obliterated, you can see the same effect in the tree behind. Whereas lighter, more contrasty areas are not affected the same way. If not the effect of NR then is this caused by heavy compression...? 

You can see the whole video here https://vimeo.com/150029132 (the screenshot was taken at 02:55) It is this kind of issue that, for me, prevents the NX1 being a go-to professional camera.

![screenshot](https://cloud.githubusercontent.com/assets/19612634/15837110/bb5984e6-2c2f-11e6-9498-75eb5fd437e8.jpg)

**Comment by WWilhelm** [comment]
Hi Tim, sorry for this late feedback...I was about to ask you for the settings you've used, I had allready a slight idea but then, I saw one of your comments (the one with your settings).
There is definitely no NR filter that causes such issues. With your settings, you just threw away about 30-35% of the entire luminance values (contrast range). And with the sharpen Filter set to -10, you gave the footage the "coup de grace". You have not only ugly artifacts but also a lot of banding on the areas with critical colours (blue values). Maybe the original file might look better, but the clip on Vimeo is...not so good. :-)
There is a lot more to say about these settings, but to be honest, I don't know if this is the right place.
I don't want to fill this thread with those kind of issues, because I think both, Otto and nea Vasile as well, want to keep this site just for modding purposes. Unless they have nothing against...then I'll be glad to talk about it.

Thanks,

Wilhelm

**Comment by kazisaab** [comment]
Hi there !
I am very new to this camera ,1 week to be precise :) 
   i did buy this camera after knowing about Hacks  are possible .

My wish list are simple 

1. Extended time  ( i have the   firmware 1.41 and its not taking the command of  up down ok  buttons  with script inside sd card .

2. I do have the Dumb adapter to use with Nikon lens  but  i cant take video as it says No lens :( 

3. .240 Frames per second Solo motion Video please 

4. Final is  is there anyway to Delete Samsung Logo  which   appears while turning off  the camera and Load any  ormy choice  as MY initial  or anything  customizeable or no logo at all please

Regards !
JT

**Comment by Chopperguy** [comment]
Hi Otto and Vasile, the new developments look very interesting.
Can I request some more features please. .. ?

The option to lock focus in Manual, to prevent the camera auto selection caf, when it is taken out of preview mode.

Focus peaking in UHD if thats possible.

many thanks

**Comment by vasile-gh** [comment]
you need to be more specific for the focus request pls - do not understand it. thx

**Comment by Chopperguy** [comment]
My problem , is that the focus I set,  gets forgotten when the camera is taken out of preview, and if I am under pressure, and forget to reset focus, the shots are ruined
outerbeat replied to another user in eos forum the following quote ....
but it is beyond my skill level, 
thats why I would love it if it became an optional mod.

start quote "
It's already hacked like 4 month ago, just not implemented in hack with any key-combo. In telnet you can set up MF mode just like this:

st cap capdtm setusr AFMODE 0x70003

That's all, camera now in MF mode, but there is no indication of that, but if you know - you can use it. Tried this just now with NX1 and 16-50S in AF mode, works like a charm, MF ring is focusing, which doesn't happens with this lense in hardware-switch AF mode. MF assist also works okay.

If anyone need this in hack - you just can use keyscan and bind one of the camera buttons with EV+ combo for that.

**Comment by vasile-gh** [comment]
So you are saying that putting the 16-50S on MF using its switch does not "stick"?
What about setting the camera in MF using menu settings (not the HW switch on the lens)

**Comment by Chopperguy** [comment]
no i'm using 16-60 pz.

**Comment by Chopperguy** [comment]
remember the focus button app, could that that be an option again please ?

**Comment by vasile-gh** [comment]
@Chopperguy "remember the focus button app, could that that be an option again please" don't get it :-(

**Comment by Chopperguy** [comment]
It  was one of the mods already developed, where you could set the focus on an object far away, and then change back and forth from a closer point and that far away point.

**Comment by vasile-gh** [comment]
You mean @ottokiksmaler's focus buttons?

**Comment by Chopperguy** [comment]
Yes ottokiksamaler's focus buttons. And thank-you for clarifying that. It is a very useful function.

**Comment by arspr** [comment]
Hey, I've just seen this "thread". I'm going to post my two (in addition to true either BBAF or AFL) main requests:

+ **Canon-like SAF <-> CAF switch on lens iFn button.** This is my most missed feature from my former Canon 7d. Period. Did I say "period"? Period again, just in case. Basically all Canons offer a button mapping which allows the camera switching between SAF and CAF (if you're in SAF you go to CAF and vice versa) _while the button is held_. This feature is just great while taking pictures of unpredictable targets (children?, pets?). Seriously, when you use it just once, you can not understand how you've lived without it before. In Samsung cameras I'd also map it to the lens iFn button because a) it really feels the natural place for this function, b) because IMO this button current features are useless at least in NX1 where you have direct access to all its mappings in other more convenient ways.

+ **AF distance tweak (DSLR-like).** Ok, a mirrorless camera cannot suffer back/front-focus issues because AF vs. main sensor misalignment. But it can suffer it because a) peripheral lens quality (remember phase detection AF relies mainly on the light coming through the outer area of your lens but the picture relies mainly on the centre of it), b) the camera tends to select a _**wrong**_ high-contrast area for AF. And I really think the b) issue is a quite more frequent than desirable one, at least in NX1. As a simple example: when focusing on a face, it usually locks on _its contour_ which could generate a slightly back-focused picture. I really think NX1 is a quite _false back-focuser_ because this high contrast edge hunger. Therefore an AF manual fix could be quite desirable (as Olympus cameras have, and they are also mirrorless, aren't they?). It could go from a simple value to any complex setting you can think of (different sets of values for each lens, different values for each focal distance, different values for different focus distances, different values around the picture zone ...)

**Comment by arspr** [comment]
Hey, this thread ( http://www.dpreview.com/forums/post/58000576 ) gave me another idea for a possible useful feature (quite similar to the _no lens shooting_ from DEV menu):

+ **An option (tick) to directly kill lens switches,** using camera menu ones instead. As example that user JanMatthys could continue using that "broken" lens switching AF/MF in the AF Mode menu... We know for sure this can be done in the AF/MF switch which actually does _nothing_ on the lens. And I suppose OIS one would be more or less the same, as the camera menus also include a grayed out Off option...

**Comment by arspr** [comment]
I don't think it's anything wrong in the mod. The problem is just the message you've got. 150 is just double of NX1 highest 80 Mbit/s. You are pushing nearly double amount of data rate against SD and its associated buffer and it has got saturated. You just need a faster card to keep on (maybe ush-2 card?). If you really wanna go Hi-pro you're gonna pay for it.

But coders should judge.

**Comment by BopBill** [comment]
I have Lexar Professional 1000x 64GB SDXC UHS-II card. 150 Mbit/s + DIS (UHD 30 fps) have not been problem before if I remember correctly. 
This is just my thought. Maybe if other users are starting to report similar issues separated mods could be a solution.
I do have the 5.02 version on my computer. Maybe I try that again.

**Comment by vasile-gh** [comment]
@BopBill @arspr how about adding a menu option to kill EVERYTHING until next battery pull (i.e. basically making the camera "factory mode" except for the patched bitrates.

Of course, menus would be gone and irretrievable until battery pull and put back.

**Comment by BopBill** [comment]
@vasile-gh That would be excellent. That way it could be possible to get the experience how much other stuff affects to usable bitrates. One could choose his priorities.

**Comment by arspr** [comment]
Sure, that could be great. But my first question for you coders is: are the mod contents actually doing anything while not launched (in addition to whichever part of it that is "hearing" for LCD+LCD/EV+EV press)? Is it consuming CPU? Or is it just using some bytes of RAM and that's all? Because if the second one is the current case I cannot see how it could affect video recording unless there's an unexpected side-effect/bug, (I suppose the "hearing" part has not changed at all from previous nx-patch versions with less included features)?

**Comment by vasile-gh** [comment]
whilst menu is off there's only keyscan running unles you have focus_stack or focus_buttons or shutter_to_rec or telnetd which need to run in order to do their stuff.
NB still waiting for @ottokiksmaler to get back :-) before I can "officially" release 5.3

**Comment by ottokiksmaler** [comment]
Hi, regarding keyscan - unless you are pressing keys it does almost nothing (it polls the system timer every second to see if it was put to sleep in the mean time) but that takes almost no cpu time. Waiting for keys also takes no resources as we use system calls made for that purpose (select) and do not try to read key events constantly. 
For illustration, even parsing full system log in real time (log watcher) takes under 0.1% of cpu time unless we are executing external command when it rises to 0.7% (plus whatever the external command actually does). 

That said, di-camera-app is very touchy and it very much dislikes waiting for anything (makes sense, samsung never actually intended is running applications alongside it). 

Regarding 5.3, I'm not sure what I should do (I've been away and working on my day work so I might have missed something here).

**Comment by vasile-gh** [comment]
@ottokiksmaler welcome back :-) you need to recompile focus_stack - it has a bug: see [here](https://github.com/ottokiksmaler/nx500_nx1_modding/issues/67#issuecomment-229121523)

**Comment by arspr** [comment]
@ottokiksmaler: (about 5.3) go to that "thread" you have two things to do:
+ Vasile discovered a bug in focus stack (latest posts)
+ Physical OK vs. Touchscreen Enter. Basically _focus stack_ config dialogue doesn't work with physical OK (at least on **NX1**), buuuut Vasile's bitrate configuration and installation dialogues don't work with Touchscreen Enter. Something fishy going here. In case it helps I posted both key-scan results in other thread:
```
Physical OK: KP_Enter
Touchscreen Enter: Return
```

**Comment by ottokiksmaler** [comment]
I have recompiled focus_stack, now it actually uses provided config file (sorry about that) and there's a possible fix for NX1 popup

**Comment by ottokiksmaler** [comment]
Sorry about this as well, added new version with OK working (hopefully) on NX1. Can someone check?

**Comment by hirsti** [comment]
Was wondering if it would be possible to have a hack that does the following:

When viewing through the viewfinder, clicking a pre defined key like AF-On or optical preview which will take the current focus position and turn on the Focus Tracking. At the moment the only way to use the focus tracking on the NX1 is to enable it and then touch the LCD screen where you want to start focus tracking.
 This tracks really well but you have to have the camera on a tripod as trying to hold the camera steady whilst holding it in front of you and trying to touch the LCD screen to obtain track focus is nigh on impossible hand held. What I would like to be able to do is have the single focus window at a set size in the middle of the screen and when viewing through the LCD something is in the crosshairs of the focus box press a button that simulates the touching of the LCD at the position on screen of the focus box that then starts the focus tracking. I think this would also work on the NX500, I know it doesn't have a viewfinder but you could still have the initiate tracking from crosshair focus point.

I was at the British F1 Grand Prix this weekend and this feature would have been awesome as the cars came down the pit straight and into the corner.

Thanks

**Comment by ottokiksmaler** [comment]
I'm actually using something similar on my NX500 (so I have no idea whether it would work on NX with EVF on, it should work with LCD on) with EV+Half-shutter 
EV_S1.sh 
/usr/bin/st key touch click 360 240
This "touches the screen" in the middle and if I have touch tracking ON it starts tracking.

**Comment by hirsti** [comment]
using the Vasile hack where do you place the .sh files for the key presses to be picked up?

**Comment by ottokiksmaler** [comment]
Should be /opt/usr/nx-on-wake/

**Comment by arspr** [comment]
Please read a variation I've made in [my former request about the Canon-like CAF<-->SAF switch](https://github.com/ottokiksmaler/nx500_nx1_modding/issues/31#issuecomment-229923875).

**Comment by arspr** [comment]
I'm no expert but I think that happens when your card is just not quick enough to save all the data from the movie.

Your used bitrate is just too high. You have to lower it.

**Comment by ricocz** [comment]
Hello Vasile and everbody! 

Many thanks to You Vasile! I love the hack. i would like one thing. No noise filtering. this is possible ? 
Thank You! regards, Richard

**Comment by ottokiksmaler** [comment]
No noise filtering in 2.5k exists, it's also like skipping (not rescaling) so it looks sharper but can have weird horizontal line artifacts. It's either a remnant of beta version of the firmware or unfinished "future" feature - either way, we currently have very little control over it.

**Comment by Bohus-Blahut** [comment]
I’d love to be able to adjust the crop size of the sensor. Especially for video. I’d love to shoot with lenses that normally vignette at the full APS-C sized frame. Magic Lantern does this on Canon cameras calling it a 2x or 3x zoom. Great for shooting with C mount lenses Thanks!

**Comment by ottokiksmaler** [comment]
C mount lenses should work in 4k as it crops down to ~1" size. I haven't been able to get a crop in 1080p.

**Comment by Bohus-Blahut** [comment]
Thanks for the amazingly fast reply! Sure... I can crop in post to get a 1080 quality image... it would just be lovely to see the image correctly while shooting. That’s probably what I use Magic Lantern for the most.

I haven ‘t done the math, but is that sensor large enough that if you did the 1” crop you could stil be recoding in 4K? That’s sort of what the new Canon EOS M50 does on accident. It would be tremendous to be able to record with some of these old lenses in 4K.

Again - thanks for getting b ack to me so quickly! I’d love to see the NX1 come to life as an even more powerful beast!

**Comment by ottokiksmaler** [comment]
In NX500, when filming in UHD or DCI 4k, you are cropping from the full sensor width to 4k pixels wide which gives a crop of 1.6 horizontally (1" would be 1.7 so it's very close and decent lenses should not vignette). You see it like that on LCD as well (so same as M50).
I only tested Angenieux 12-120 and it worked great (it is quite expensive though).

**Comment by ottokiksmaler** [comment]
Do take care that you need an appropriate adapter that intrudes well into the body (~8mm) as c mount flange is less than NX one. Otherwise you lose infinity focus.

**Comment by fxcam** [comment]
Any life left in this nx1 conversation? Does anyone know of a way to get a completely clean live hdmi preview out of the nx1? HDMI out put is clean for video playback obviously but would love to have the ability to stream 'live' video from the hdmi output. 
Many thanks... and my apologies if the topic has been exhausted!!

**Comment by ottokiksmaler** [comment]
You should be able to have it out of the box. I don't have NX1 but NX500 has clean HDMI out (1080p). Maybe ask on dpreview.com?

**Comment by Bohus-Blahut** [comment]
How about anamorphic modes? This is something that we see in Magic Lantern as well. The camera records in a 4:3 aspect, and the live view scales the image appropriately  Perhaps this wouldn't work at shooting at full 4K, but perhaps we could get at least 3K or 2K worth of image quality?

I can shoot with anamorphics on the NX1, and then just scale in post, but how much cooler would it be to do it all in camera?  Thanks for considering!

**Comment by ottokiksmaler** [comment]
That would be very cool. I don't know about NX1 but on NX500 the CPU is completely consumed during video recording and running anything even remotely CPU intensive results in hanging camera and requires battery removal. Sorry
