### ISSUE TITLE
NX500 debug mode is on by default ????? Why?

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#32]
`ls -l /opt/etc/.debugmode`
`-rw-r--r-- 1 root root 27 Apr 30  2015 /opt/etc/.debugmode`

Wondering what would be the result of renaming this file and testing video recording - might bring some performance improvements.

**Comment by ottokiksmaler** [comment]
Did it. Without it the keyscan was not started? It seems. PID is still 248 so still custom image. /dev/log_main still exists.
Have to see what happened.

**Comment by gitvasile** [comment]
No idea, did not do any test recording because if any effects could be seen it would be at extreme rates.
I doubt it would have an effect on keyscan, what i hope is that it would decrease in-camera logging which should increase stability. But again, the effect would only be visible at high bitrates.

**Comment by ottokiksmaler** [comment]
Btw, fastest way to hibernate seems to be 
```
echo -n disk > /sys/power/state
```
