### ISSUE TITLE
NX-KS (open topic)

### ISSUE THREAD

**Issue by KinoSeed** [ottokiksmaler/nx500_nx1_modding#34]
It's easier to follow/answer comments using an "open issue", than below the code.

Please post any comments, questions, requests regarding NX-KS here.

**Comment by KinoSeed** [comment]
btw, not sure where the topic about the hibernation-mod went,
just wanted to remind you, that **/opt/** and **/opt/usr/**  are separate mounts.
( NX-KS uses /opt/home/scripts ). If one of the mounts does not survive the restart, maybe the other will?

**Comment by vasile-gh** [comment]
Neither survives. /opt and everything below is unmounted and remounted during hibernation /wake-up

**Comment by vasile-gh** [comment]
Also this needs to be balanced with the fact that we do not want to have to refresh hibernation image every time the mods evolve

**Comment by KinoSeed** [comment]
/opt/usr/  is not below /opt/, it looks like it's a completely different mount
I did a quick try to install a service in rescue, which to turn on the mod on /opt/home/scripts/ but didn't work. 
maybe we should patch the rescue mount before.. "rescue"?
or even try to replace di-camera-app there with the NX1's?

**Comment by vasile-gh** [comment]
I am aware of that, I meant it purely from the point of view of pathnames. 
You need to spend some time to understand how systemd works and how Samsung implemented their hibernation process. 
What you tried cannot work, period.

**Comment by KinoSeed** [comment]
: ) ok Vasile

**Comment by Tommixoft** [comment]
@KinoSeed  can you please add to your mod or write to me - how cna i make 4K (the real one, not 2160p) become 2.5k? you use 720p and mpeg resolutions, can you help me with offset how can i replace 4k with 2.5k? :)

**Comment by KinoSeed** [comment]
@Tommixoft , 
./poker $(pgrep di-camera-app) 0x1af064:5a8ea0e3 0x1af068:0aaca0e3
have fun : )

**Comment by ottokiksmaler** [comment]
Did anyone try replacing dfmsd 2.5k mode bitrate? It might be without issues plaguing this 2.5k mode (quasi interlace and the like)

**Comment by KinoSeed** [comment]
I haven't, but if there's no change in quality on the 4K, probably won't be much different.
@Tommixoft , how is the quality now? any change?

**Comment by Tommixoft** [comment]
@KinoSeed THANKS. will test when im get back home.  I want to replace 4k mode with 2.5 because when i use 640 mode, some of 2.5k videos have stange lines in video (dont know how it's called but i saw in forums people have this too) but in many cases - i do not have lines. SO i thought i may try to use 4k mode repalce wtih 2.5k maybe it will have best options and 2.5 will be superb and no more lines.. but have to test, and today is crappy rainy day :)

**Comment by KinoSeed** [comment]
I ran a few test, but the "lines" you talk about I get maybe once in 50 videos, so it's not often. From the clips today didn't get one bad video, however I can't see a difference between 2.5K on DC. They look identical quality-wise.

**Comment by Tommixoft** [comment]
@KinoSeed i dont use 4K anyways [using UHD because of it's kind a todays format and my tv support it right from camera] so for me no difference where i set 2.5k, but i was thinking maybe quality will get better.
Strange about those 'lines', why they appear. And ye sthey are rare but you know... if you on vacation and filming something and then after get to home see on pc that it's full of lines -not good :D

**Comment by Kai-Angne** [comment]
Hi guys, thx a lot for your great work! 
It would be nice to have the UHD 120fps mode (1920_1080_120p) accessiable from within the gui. Is it possible? If there is a poke for this mode, i can patch it myself ...

**Comment by KinoSeed** [comment]
@Kai-Angne if you are looking for 20fps at higher resolution, yes you can change the resolution for 720p selection to FHD or UHD, but it will not really record with 120fps (the video will look sped-up, but will not have real 120fps capture), and besides the quality is too bad to be useful in any way.

**Comment by KinoSeed** [comment]
no longer monitored - closing
