### ISSUE TITLE
Feature request: rsync to external drive

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#51]
Hello. I saw some time ago you made rsync. Can we make mod who whould execute rsync and tell rsync to sync (well only copy) whole sd card to usb HDD attached via OTG cable to nx camera?
This feature would be KILLER feature.

**Comment by vasile-gh** [comment]
OTG is not supported on NX cameras out of factory, and neither me nor @ottokiksmaler know whether this might be made possible.
I did rsync because I was tired to shuffle cards between camera and my PC :-) - gets tiring at a point and puts undue stress on the power switch (and the battery cover on NX500).

Syncing on a wifi portable disk like [this](http://www.fantec.de/produkte/kabellose-freiheit/wlan-speicher-docking/produkt/details/artikel/1636_fantec_mwid25_schwarz/) is much easier and I plan to do it sometime...

**Comment by vasile-gh** [comment]
sorry :-(. but keep in mind you would do it every night and I doubt you would fill 90GB in a day - unless you do high bitrate video that is...

**Comment by Tommixoft** [comment]
Not i a day-i mean 90GB in 2 weeks. :) With my canon i could last 2 weeks with 32GB easily. with samsung barely :) I neve rtake laptops in my vacations..so ether i have to buy cards or find a way to copy photos to external storage without pc :) 
I doubt that those wifi disks supports copying from usb.
