### ISSUE TITLE
Flash wear

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#57]
@vasile-gh why you say that  changing bitrates uses flash? is this some stupid linux stuff or what? You modify ram not eMMC. 

"INSTANTLY available upon
    cold startup (NB. you will have to "Make default" them - I did not
    make it automatic in order to reduce camera flash writes)"

**Comment by vasile-gh** [comment]
Samsung **only** stores the settings in non-volatile memory on power off. If you pull the battery the changes since most recent power on are lost.

I believe they had a **good** reason to do so since it is actually more complicated - programming-wise - to arrange that instead of simply writing any changes when they are made.

That is why for which I built the mod to behave as close as it can to the way Samsung does things: not **permanently** save anything until **told** to do so. Unfortunately I am not (**yet** - watch this space - I have a plan) in a position to intercept turn-off and completely emulate this behaviour in my mod, so I did the next best thing: have a "**make default**" button that will do so.

And to answer your question, the only reason I can see for Samsung behaving like that is if they wanted to avoid excessive flash writes. So I prefer to be careful and follow their lead.

**Comment by Tommixoft** [comment]
@vasile-gh  thanks for answer but still did not understood a thing :D What settings? Bitrate-mod hack do not store any settings, only changes "ram". I mean you dont use prefman to store bitrates and resolutions so you dont use flash and that's why i dont understand why you "Save" flash which your mod dont even use.. Yes it uses flash to store files..but that's it..no more writes. you maybe creating default values file and on load read it and path ram, but that's only 1 write.. no?

**Comment by vasile-gh** [comment]
Yes, the changes are made in RAM - the di-camera-app is patched, but in order for the patch to be available immediately upon start-up the settings must be saved **somewhere** so that the patch is done automatically upon startup. And they can only be saved on camera flash.
So I am not saving the patched di-camera-app, but rather the list if patches that need to be (re-)made upon camera startup, since the non-patched app will be running at startup .

**Comment by Tommixoft** [comment]
I understand that - so if i click Set as defaults once, you create once my settings file(s) and after that only read them never create again and again new ones..Yes? so if i do not change bitrates 200x a day-there is no what to be afraid of wear yes? :)

**Comment by vasile-gh** [comment]
correct

**Comment by Tommixoft** [comment]
Nice. so you just prevented people from saving settings to file whenever they change value. so you keep it in memory and only if people want to use it always-have to set as default. :)
In-fact button names SAVE settings or just Save sounds more straight forward :) Anyways thanks for explain. I was thinking maybe because i now set as default script somehow writes to flash a lot more.
