### ISSUE TITLE
bug: After update settings gone

### ISSUE THREAD

**Issue by Tommixoft** [ottokiksmaler/nx500_nx1_modding#64]
WTF. I was using nx-on-wake and nx-patch v5 Today upgraded to 5.2 and all my settings gone. No more bitrates or resolutions, why?? This should not happen.
Ether make versions less frequent or keep backwards compability. With every new version everything changes.
Bad design i would say. Some criticism is good i think :) Now have to reflash FW to be sure all is clean... and no left overs.. 
I know you do this not for commercial reasons but this still.. YOU NEED NORMAL WEBSITE. GitHub is for sources, not for websites.
And put in website only 100% stable things, no updates every 3 hours. As i said i can help with it. I will be gone for 2 weeks, but after that-i can. I just dont want to make website and you dont use it.

**Comment by vasile-gh** [comment]
@Tommixoft I would appreciate a bit more polite tone here. Also, do not forget this is a developer site - I notify "stable" releases on dpreview. On github things are liable to change more quickly. It is true I recently did some more frequent changes but I did them because I felt they were important enough to warrant it.

Also, if you feel like it I will certainly not prevent you from putting together a nice website and I am (almost) sure no-one here would mind :-). My issue is not with a website but rather with the effort to keep it up and manage it. Besides, I do not feel like github is lacking a "must have" feature and I would be quite happy to keep things as they are now; but again, that is just me.

Yes, it would be good to have the settings saved between upgrades - feel free to implement that, the scripting in the pack is not rocket science. I am probably not going to do it unless it will turn out that my current objective: move away from scripts etc is unfeasible, because if it is feasible, the effort I would need to put in saving settings might be better spent on something that would not become obsolete when I move away from the current system.

**Comment by Tommixoft** [comment]
How polite is to remove people settings with newer mod version? not polite, so you could be more polite too :)  At least add some warning. and you should make some bin to generate menus, so you could save settings with one standard and read it with every new version.
Also some kind of "mod gui" could be created only for bitrates and resolutions. So it reads values from RAM, not from file. This will eliminate of generating menu files, and will allow you to back to menu after value was set.

Im afraid about website-that if i buy domain, create website - you may refuse to use it. and it just be waste of time and money. Unless you give me permission to upload your mods myself and so on. Dont want KinoSeed story. :)

**Comment by vasile-gh** [comment]
ok I thought of a way to preserve bitrate settings across upgrades - it will be included in the beta I will post soon.
