### ISSUE TITLE
nx-patch v5.3 issues

### ISSUE THREAD

**Issue by vasile-gh** [ottokiksmaler/nx500_nx1_modding#71]

**Comment by arspr** [comment]
**NX1**

While trying to narrow down the _focus stack_ mysterious disappearing messages (without luck :( ), I've noticed this one (which is _not_ exactly a bug):
+ Stored _focus buttons_ distances are fully dependant on the **focal distance** of the lens (at least on 16-50S). Example 50mm distances are MUCH longer in 16mm but, interestingly, shorter at about 35mm. My only scare about it: nothing seems to happen in the lens, but I think I'm getting out of bounds post infinite focus distances at 16mm. _Could it be harmful for the lens?_ If possible maybe a focal distance check could be added which wouldn't allow the _focus buttons_ to work if the focal distance is, let's say, outside a ±10% margin.

**Comment by ottokiksmaler** [comment]
No harm to the lens, it cannot move past whatever the limits are in the lens (there is another call for that specifically in st command, to see the range). 
Every lens (that I have) can actually focus significantly closer and far beyond infinity as there are actually two sets of data returned (like maximum and *real* maximum value). You can see this while in SAF with DMF on, you focus as close as possible and then while holding half-shutter you continue to move focus ring and it focuses even closer (useful for macro). 
Unfortunately, I know no way to control the zoom precisely, I can either put it in wide or tele position and that's it. This can be very frustrating with PZ lens as it defaults to 16mm when turned off/on which makes it mostly useless for use with focus buttons unless everything is done during one shot (or at extremes of zoom range).
Also, even 10% (or anything not exactly the same) will give you very much out of focus images - nobody likes those :)

**Comment by arspr** [comment]
Ok, otto. My only _concern_ was about possibly lens health, but there seem to be quite good doctors here...

**NX1**
About the _focus stack_ messages. I'll make more test (no more time now) but *I think*:
+ The messages are available after installation of the mod.
+ They survive warm boots (power off/on cycles).
+ But they don't survive cold boots (battery out cycles). _focus stack_ works flawlessly but NO message appears any more since a cold boot.

(I'm starting to doubt, but I really think at least till 5.3beta8, I could always see far/near messages. I'll downgrade to that version later...)

**Comment by arspr** [comment]
**NX1**

Well, clearly the important changes for _focus stack_ messages have occurred between beta8 and beta9. (Beta10=Release works like beta9 in this regard).

+ Beta8 had **different** far/near and info messages. They were in a blue background (as nx-patch GUI) and they covered the whole width of the screen.
+ Beta9 ones have a black background and they are only a rectangle (they don't cover the whole screen width).
+ Beta8 messages survive cold boots. But there's no progress indicator even just after installation. Only far, near and info.

(I hope this helps you tracking down WTH happens).

I cannot think of any other tests about it. If you want me to do anything else just ask.

**Comment by ottokiksmaler** [comment]
Hm, it seems the version in zip is from two days ago, not the latest version from last night. Would it be possible for you to download it to SD card and then  execute it from telnet session? 
https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/focus_stack?raw=true

**Comment by arspr** [comment]
Sure, just two things:
+ I _supposed_ beta10 and release were the same zip. Beta10 was supposed to include your very last version (vasile was in fact waiting for your latest version). Could you check it? Do I also test "release" just in case?
+ I'll test your standalone version ASAP. But remember that beta9/10 issues happened _after_ a cold boot. But a boot (warm or cold) kills telnet... How can I simulate it? (Or doing the telnet thing is not equivalent to a "installation" each time?)

**Comment by ottokiksmaler** [comment]
Telnet is not related to installation. Starting from telnet should be exactly the same as from mod_gui. On a phone, sorry for brevity

**Comment by arspr** [comment]
**NX1**

@ottokiksmaler about that _focus_stack_ through telnet: **AT LEAST!!!**, not perfect but  _nearly_:

+ Far/near/info messages are the "old fashion" ones (blue, whole width).
+ I don't get the "initial" progress message. (Which said something like "I'm taking nn pictures with a mm s delay").
+ But I always get the "#xx of nn" ones after each picture. This messages are the "new fashion" ones (black, adjusted reduced width).
+ No problem with either cold or warm boots before launching telnet and the focus_stack "app".
+ BTW. This _standalone_ app doesn't use the same configuration storage area. Within nx-patch version I have 3 pictures 1 second (_fast testing, you know_). This standalone one has read my old 6-1 configuration. I suppose this is "normal" as vasile has to do something to integrate those parameters with the rest of the nx-patch mod. Buuut, you are leaving trash behind you... somewhere in my system I have a file saying "6-1". @vasile-gh: **_shouldn't nx-patch delete that file upon installation/upgrade?_**
+ BTW (2) are there more rubbish files like that? (I'm thinking in _focus buttons_).
+ BTW (3). This standalone focus_stack still says v2.3**0** (yes, you have even hundredths). @ottokiksmaler: shouldn't you update the version number a bit more frequently ;-) ? (Otherwise it's pretty useless for bug vs version tracking).
+ BTW (4). A possible enhancement. Info message stays displayed a _**fixed**_ (a bit too long?) time. If possible I'd make it disappear on any key press/Touchscreen action. You easily get the false impression the app has frozen. (A cosmetic fix nevertheless).

**Comment by arspr** [comment]
**NX1**

@vasile-gh: While doing the focus stack tests through **telnet**, it has remained on after a power off cycle. I haven't been able to reproduce it any more... (I'm posting it just in case).

**Comment by ottokiksmaler** [comment]
To use the same configuration area start it with 
/mnt/mmc/focus_stack /tmp/focus_stack.cfg
That is the way it's started from Vasile's mod pack. The file is in /root/focus_stack.cfg if you want to delete it. I keep it there for my needs, mod packers put it where they need it to be. Same goes for other utilities. 
Info message displays long on purpose to make people read it, could make it disappear on touch. 
Version number is my bad :)

**Comment by arspr** [comment]
**NX1**

I've just noticed it:
You can launch **multiple instances of _focus stack_ and/or _focus buttons_** (through successive LCD+LCD with those apps previously running). I'm no coding expert but this really seems asking for gratuitous trouble... I'd make LCD+LCD (EV+EV) kill any previously running mod.

**Comment by ottokiksmaler** [comment]
Btw, if you want to make this version replace the one in mod pack do 
cp /mnt/mmc/focus_stack /opt/usr/nx-on-wake/focus_stack 
sync ;sync ;sync

**Comment by ottokiksmaler** [comment]
No. I'll make focus stack / buttons kill themselves if they already are running in the next version.

**Comment by arspr** [comment]
Good, I'll replace it later (this version is better). If you launch new versions of any of them (cough, cough, cough: messages for "position nn set" in _focus buttons_?) do not hesitate "using" me as your "favourite" beta tester... ;-p

**Comment by ottokiksmaler** [comment]
Will do, I have some things that need to be treated on nx1. Thanks

**Comment by arspr** [comment]
He, he, I was just going to do the cp (copy?) thing.
So here you are:
```
[root@drime5 ~]# cat /proc/sysvipc/msg
       key      msqid perms      cbytes       qnum lspid lrpid   uid   gid  cuid  cgid      stime      rtime      ctime
 555026525          0   666           0          0     0     0     0     0     0     0          0          0 1465802826
 605358173      32769   666           0          0     0     0     0     0     0     0          0          0 1465802826
1679099997      65538   666           0          0     0     0     0     0     0     0          0          0 1465802826
      2014     196611   666           0          0     0     0     0     0     0     0          0          0 1465802826
      4102     229380   666           0          0     0     0     0     0     0     0          0          0 1465802826
      4103     262149   666           0          0     0     0     0     0     0     0          0          0 1465802826
     34856     294918   666           0          0   301   257     0     0     0     0 1467807640 1467807640 1465802833
 831084980     327687   666           0          0     0     0     0     0     0     0          0          0 1465802833
 404031581     360456   666           0          0   244   244     0     0     0     0 1467813713 1467813713 1465802833
 585892440     393225   666           0          0   244   244     0     0     0     0 1467813713 1467813714 1465802833
  34932829     425994   666           0          0   244   264     0     0     0     0 1467813834 1467813834 1465802833
1622774141     458763   666           0          0   244   265     0     0     0     0 1467813715 1467813715 1465802833
1176997043     491532   666           0          0   244   266     0     0     0     0 1467807866 1467807866 1465802833
 100383028     688141   666           0          0   244   407     0     0     0     0 1467807751 1467807751 1467807716
       352     557070   666           0          0     0     0     0     0     0     0          0          0 1467807671
       353     589839   666           0          0     0     0     0     0     0     0          0          0 1467807671
       354     622608   666           0          0   291   291     0     0     0     0 1467813781 1467813781 1467807671
[root@drime5 ~]# 
```

BTW, we are probably cannibalising the 5.3 issues thread. I suppose it's better if you open another different thread for these things, don't you think?

**Comment by arspr** [comment]
**NX1**
**Possibly very IMPORTANT**
[See this post by Pavel Masek and my direct answer in dpreview](http://www.dpreview.com/forums/post/58041326)

Summary: it seems at least NX1 completely shuts down, (like a battery out cycle), after some time in Power Off. So you cannot distinguish between cold and warm boots...

It would render _killall_ unusable for practical uses. (And _make persistent_?)

I'm trying to reproduce the issue. A 9h30min window has not generated it. I'll leave the camera in Power Off till tomorrow morning. (But I'm nearly sure it does actually happen because the Telnet issue explained above).
