### ISSUE TITLE
Speeding up "st app *" functionality

### ISSUE THREAD

**Issue by ottokiksmaler** [ottokiksmaler/nx500_nx1_modding#73]
**Notice:** Currently tested on NX500 with fw1.12 - should work on NX1 as well since the message key is the same (in /proc/sysvipc/msg file as checkd by @arspr)

ST tool communicates with both di-camera-app and hardware of camera via various means, one of which is messaging to di-camera-app (used for all commands starting with `st app [whatever other parameters]`.

Messages are sent to di-camera-app via key 0x8828 (34856 decimal) as 208B messages of following format:
- Every part of message is "string" padded to defined length by null characters (\0)
- First and last "part" are 4B long, middle ones are 20B long
- 0-4B - Number of "parts" not including this one, for example 5\0\0\0 (5 and three nulls)
- 5-24B - First part, always /usr/bin/st\0\0\0...\0 - 20B
- 25-44B - Second part, etc.
- 205-208B - All zeros - might have some meaning - not sure yet

Example: when invoking `st app nx key single ok` to "click" OK button, the message sent is:
"\6\0\0\0/usr/bin/st\0\0\0\0\0\0\0\0\0app\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0nx\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0key\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0single\0\0\0\0\0\0\0\0\0\0\0\0\0\0ok\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"

We can emulate this without doing everything else `st` does before "useful" part thus reducing delay in operations:

```
[root@drime5 ~]# time /mnt/mmc/stapp "app nx key single ok"

real    0m0.045s
user    0m0.000s
sys     0m0.010s

[root@drime5 ~]# time st key click ok

real    0m0.392s
user    0m0.300s
sys     0m0.020s

[root@drime5 ~]# time /mnt/mmc/stapp "app lens pzoom tele" 

real    0m0.008s
user    0m0.000s
sys     0m0.000s

```

So, _much_ faster and with lower CPU time usage. 
Please do note that the execution itself is asynchronous so the clicking or zooming takes some time after the command to finish. That said - this allows for somewhat better control of zoom as it is possible to do something like

```
/mnt/mmc/stapp "app lens pzoom tele"; sleep 0.05; /mnt/mmc/stapp "app lens pzoom stop"
```

This will move the zoom in ~1mm. Not truly precise, but useful as illustration. 

This also eliminates the need for launching external program when we need to emulate:
- pressing keys
- changing modes (P/A/S/M/...) and drive modes (S/CN/CH/...)
- flash function
- photo capture 
- video record start/pause/stop
- iZoom
- control power save timers
- turn off the LCD/EVF/etc...

See [here for available _st app_ commands](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/master/ST%20Commands.md).

Early version of **stapp** is available for download and testing [here](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/dev/stapp) while the source is [here](https://github.com/ottokiksmaler/nx500_nx1_modding/blob/dev/stapp.c).

You can invoke it from telnet for example with:

```
/mnt/mmc/stapp "app nx key single menu"
/mnt/mmc/stapp "app nx capture single"
/mnt/mmc/stapp "app mode custom1"
/mnt/mmc/stapp "app lens pzoom tele"
```

Or use it from C program by invoking 

```
int send_message(char * message_in)
```

Like this

```
send_message("app lens pzoom tele");
```

**Comment by arspr** [comment]
Good Chinese (or Etruscan) lesson ;-p

Can I help with something _veeeeery_ specific for non-Chinese (or non-Etruscan) speaking people?

(Tomorrow)

**Comment by ottokiksmaler** [comment]
You could try some of the examples mentioned here and report back whether they work on nx1.

**Comment by arspr** [comment]
```[root@drime5 ~]# time /mnt/mmc/stapp "app nx key single ok"
Adding at 4 /usr/bin/st(11)
Adding at 24 app(3)
Adding at 44 nx(2)
Adding at 64 key(3)
Adding at 84 single(6)
Adding at 104 ok(2)
Message:
6___
/usr/bin/st_________
app_________________
nx__________________
key_________________
single______________
ok__________________
____________________
____________________
____________________
____________________
____

real    0m0.032s
user    0m0.010s
sys     0m0.010s
```
This has the effect of pressing OK (as expected I suppose)


```
[root@drime5 ~]# time st key click ok

real    0m0.391s
user    0m0.280s
sys     0m0.040s
[root@drime5 ~]# 
```
The very same OK press.



```
[root@drime5 ~]# time /mnt/mmc/stapp "app lens pzoom tele"
Adding at 4 /usr/bin/st(11)
Adding at 24 app(3)
Adding at 44 lens(4)
Adding at 64 pzoom(5)
Adding at 84 tele(4)
Message:
5___
/usr/bin/st_________
app_________________
lens________________
pzoom_______________
tele________________
____________________
____________________
____________________
____________________
____________________
____

real    0m0.010s
user    0m0.000s
sys     0m0.000s
```
Nothing has happened, but I don't have a PowerZoom lens...


```
[root@drime5 ~]# time /mnt/mmc/stapp "app nx key single menu"
Adding at 4 /usr/bin/st(11)
Adding at 24 app(3)
Adding at 44 nx(2)
Adding at 64 key(3)
Adding at 84 single(6)
Adding at 104 menu(4)
Message:
6___
/usr/bin/st_________
app_________________
nx__________________
key_________________
single______________
menu________________
____________________
____________________
____________________
____________________
____

real    0m0.010s
user    0m0.000s
sys     0m0.000s
```
Menu key pressed



```
[root@drime5 ~]# time /mnt/mmc/stapp "app nx capture single"
Adding at 4 /usr/bin/st(11)
Adding at 24 app(3)
Adding at 44 nx(2)
Adding at 64 capture(7)
Adding at 84 single(6)
Message:
5___
/usr/bin/st_________
app_________________
nx__________________
capture_____________
single______________
____________________
____________________
____________________
____________________
____________________
____

real    0m0.048s
user    0m0.000s
sys     0m0.020s
```
Picture (with AF) taken.


```
[root@drime5 ~]# time /mnt/mmc/stapp "app mode custom1"
Adding at 4 /usr/bin/st(11)
Adding at 24 app(3)
Adding at 44 mode(4)
Adding at 64 custom1(7)
Message:
4___
/usr/bin/st_________
app_________________
mode________________
custom1_____________
____________________
____________________
____________________
____________________
____________________
____________________
____

real    0m0.011s
user    0m0.000s
sys     0m0.000s
```
PASM dial changed to C1 although it remains physically in A.

Therefore, I think everything had gone flawlessly. Congratulations!!!

**Comment by ottokiksmaler** [comment]
Hi, If someone is willing to test (yet another try of) BBAF on NX1 I have put up a file here
https://github.com/ottokiksmaler/nx500_nx1_modding/blob/dev/bbaf
that needs to be saved to SD card and started from telnet session (for now). Also, AEL button should be set to AFL or AFL Hold or AEL/AFL or AEL/AFL Hold.

- What does this program do? 
- It listens for AF-ON button events and will "click" AEL on AF-ON release and again on AF-ON press - in short - if it works as it should on NX1 it should disable AF while AF-ON is **not** pressed and allow AF while AF-ON **is** pressed.

With this new approach to emulating keys there should be no real delay (<50ms) which should make this useful. This should also work with AF-C and AF-S - but, again, i have no way to test as I don't have NX1.

**Comment by stf1x** [comment]
I am happy to see that bbaf is still on the agenda.  Will test it soon but I need 1week since I am travelling.

**Comment by arspr** [comment]
I'll also test ASAP. (But not till tomorrow at least).

Nevertheless I don't like your requisite for AEL being set at an AFL function, _at all_. I want AEL being AEL. Please tell me this is just a requirement for this test version of _bbaf_.

**Comment by ottokiksmaler** [comment]
Something needs to activate focus lock, if not AEL is there some other button that can do that?

**Comment by arspr** [comment]
I would activate it through a tick like your shutter-to-rec. And it should be "persistent" so it should be automatically activated on camera restart no matter either warm or cold boot.

**Comment by arspr** [comment]
**NX1**
Extremely quick test with bbaf. _And I haven't changed AEL. It remains in AEL_. And AF-On is in (AFStart + Lock). I'm on SAF:

- AF-On triggers AFStart and then AFL as it remains selected in its setting. This is a switch. One press: AFStart+ AFL. Next press: AFL release (no AF Start). Next press AF Start+AFL. (And so on).
- It also triggers AEL but only while held. I suppose this is your mod in action...

**BTW. The real reason for this post**. I see in the telnet client a lot of PRESSED _key_ / RELEASED _key_. But _key_ is not a name as you asked to post me before with _mod_gui_ but a number. And I can see Full Shutter (126) against Half Shutter (125) which I couldn't before. **_Do you want me to post the whole list of keys on my NX1?_**

(And sure. I'll continue with _bbaf_ tests)

**Comment by ottokiksmaler** [comment]
It should actually activate AEL while not pressed and deactivate AEL while pressed. I guess it depends on what the state is before you press it. To emulate Nikon like BBAF I think it should be set to AF start (without lock) and AEL to AFL Hold. 
The codes you see are low level numeric codes (used by keyscan as well) - you can see them all in keyscan source code with their names. The codes mod_gui sees are higher level (they are actually names used by graphical user interface).

**Comment by arspr** [comment]
How the hell do I try to explain everything I'm seeing? Let's try.

- **First of all**. Samsung people are **PLAINLY STUPID**. Stock software has an AFL function in AEL button that NEARLY works (_although it means you lose AEL which is also BAD, or that you do AEL+AFL at the same time which is also BAD_):
 - AFL option in AEL button does AFL without triggering AF Start. Good. You retain AF control with Half-Shutter and then you can stop focus with your _AFLed_ AEL button. (And you can chose if it survives just one shot: _AFL_ option, or if it survives till you deactivate it again: _AFL Hold_ option).
 - AFL option in AEL button does not lock Command Dials. GOOD (2). In opposition to AFL option achieved through on AF-On which locks Command Dials. _(Are you crazy Samsung guys? Why did you do this STUPID thing? If you were capable of doing it right once, WHY THE HELL didn't you do it right ALWAYS!?!?!?!?!?!)_
 - AFL option in AEL button does not lock the Custom Wheel (around the direction keys). GOOD (3). (Another "are-you-crazy" here)... Buuuuuuuuut it does not survive if you operate on it. If you touch the custom wheel AFL is disengaged. WRONG.
 - And the worst of all. If you are in Continuous Shooting, while Full shutter is pressed, (you are taking pictures...) AEL button don't work. (Nor AF-On does BTW). You cannot toggle AFL on/off. If you started with AFL you take all your pictures with AFL, if you started without AFL you take all your pictures without AFL. WRONG, VERY WRONG. _**This is going to kill your mod in CAF + Continuos shooting**_. Further explanation below.
- Another difference between AFL from AF-On and AFL from AEL. Within AEL AFL you lose the focus area indicator. WRONG. You don't see where the focus point is located. This not happens with AF-On AFL...

**Conclusion: AFL function offered by AEL key mapping is also buggy.**

- Your _bbaf_ mod seems to just call AEL button (with whichever function it has assigned) on its press, and it deactivates that function on release. 
 - Basically you are turning AEL button behaviour from a toggle one to a work-while-held one, and assigning it to AF-On.
 - You are DUPLICATING AEL. The true AEL button keeps working as a toggle one and, in addition, AF-On is a new AEL button but with a work-while-held behaviour (nearly).
 - I said "nearly" because it's not a work-while-held behaviour but actually a "do-the-opposite-thing-you-where-doing-before-being-pressed while held".  If I start with _AEL-feature off_ (whichever it is), I get _AEL-feature on_ while AF-On is pressed. If I start with _AEL-feature on_, I get _AEL-feature off_.

- AF-On still does whatever it does. So it could interfere with the AEL button feature.

- But if you set AEL button to AFL Hold (better than only AFL) and AF-On to AF Start (and only to AF Start, not "AF Start + Lock"), and if you start with AFL toggled on, _**you get the better bbaf we can actually achieve for CAF**_ IMO.

- _**But it's not good enough and I don't see how it could be made better with this procedure**_. Because Full Shutter overrides whatever you do on AEL/AF-On buttons, you cannot toggle AF on/off while you are actually taking pictures. If you started taking pictures with AF-On pressed, (AF on), it will remain on through all the set even if you release the AF-On button. (And vice versa). 

- In addition: **it doesn't work in SAF**. It really seems the AF Start part intrinsic within AF-On is launched (well, attempted to be launched but blocked by AFL) _BEFORE_ that AEL button AFL is disengaged by your mod. So it doesn't focus at all...

- Another drawback: as you are using AEL AFL you don't normally see where the focus point is located...

- Another drawback: you have to remember to:
 - Turn the feature on (through Telnet right now, through a GUI option in the future).
 - And press AEL button to turn its AFL feature on. If you don't do this step but only the former one you get a very strange behaviour... And remember that AELed AFL does not survive Custom wheel operation (and, as example, I have it assigned to ISO, so I operate on it quite frequently).

- And the final drawback: for this trick to work I have sacrificed AEL feature as the very first step... I need AEL button to lose its natural AEL feature. 

**My opinion.** Too many **_weird_** things. I really feel this is another dead end for either a true bbaf or a true AFL feature...

**Comment by ottokiksmaler** [comment]
Yup, sorry you had to do all that testing but I thank you for it as now I can give up (at least for now) on bbaf as there are several bugs that just make it very very hard to enable proper BBAF. 

Closest thing we had was switching to MF and back to CAF with AFON button but it takes way too long to be useful (I got it down to 0.3s but that's eternity when shooting sports). 

It seems proper BBAF will have to wait for more serious hacks (that I cannot really do as nx500 doesn't even have afon button :) 

Thanks for your effort again.
