### ISSUE TITLE
Batch recording only records one file

### ISSUE THREAD

**Issue by mbriney** [ottokiksmaler/nx500_nx1_modding#84]
I'm running the NX-KS version 2.66.  When running batch recording if I set the recording duration it only records one video for the length that I input in the UI, it does not automatically start-up the next recording.  I have tried setting the duration to 60 minutes, 30 minutes and 5 minutes, all result int he same. 

If I set the length to anything higher than 74 minutes the memory leak happens and the recording is corrupted.  

I'm using the NX1, my power save settings are set to 30 minutes (maximum).  Is there something else I should be considering?

**Comment by KinoSeed** [comment]
@mbriney , just tried it with 1 minute, and it works fine on the nx500.
Does your video complete to the full end of the time period? (making sure it doesn't crash due to high-bitrates along the way)

please consider writing about any issues on the facebook page, as there is a good chance I'll never see your messages here.
https://www.facebook.com/NXKS2/

**Comment by mbriney** [comment]
Hi @KinoSeed if I set it for 1 minute it will successfully record a single one-minute clip but it doesn't then continue to record a second 1 minute clip.  

It was my understanding (and maybe I'm wrong) that you could set the duration and it would continuously record video starting and stopping the clips at the duration you specify?

**Comment by KinoSeed** [comment]
It should automatically start recording new clips after it is done, and it does that successfully here (on nx500). 

So I'm not sure if that's NX1-related problem, or isolated case.

@ottokiksmaler , stapp works with NX1s too right? 
I changed to sending a rec-press key with it, and on NX500 it is working, so I'm not sure what is the problem here.

@mbriney , I'll make a new version as soon as I have my coffee, and change the way recordings are started, so look for v2.74 a bit later today, and let's hope it will fix the issue.

**Comment by mewlips** [comment]
I tested with my NX1, batch recording is just stopped after the first recording.

In brec.sh script,
```
do
      /opt/usr/nx-ks/stapp "app nx record start"; sleep 1.5; ticking $recording_length
      tii=($(systemctl show-environment))
      for i in "${tii[@]}"; do if [[ $i == "rec="* ]]; then rec=${i:4}; fi; done
      /opt/usr/nx-ks/stapp "app nx record stop"
done
```
On NX1, second execution of 'start' command is just ignored.
so, die in ticking function.

I edited the script like this. 
```
do
      /opt/usr/nx-ks/stapp "app nx record start"; sleep 1.5; ticking $recording_length
      tii=($(systemctl show-environment))
      for i in "${tii[@]}"; do if [[ $i == "rec="* ]]; then rec=${i:4}; fi; done
      /opt/usr/nx-ks/stapp "app nx record stop"
      sleep 2
done
```
with this modification, batch recording on NX1 is working.
'sleep 1' is sometimes not enough.

And, 'st app nx record stop' and 'st app nx record start' command is the same.
both commands are just toggle the recording state.

**Comment by mbriney** [comment]
@mewlips and @KinoSeed both of you guys are awesome, let me know where I can send coffee money for all of your work!

**Comment by KinoSeed** [comment]
In previous versions I was just invoking a click of the rec-button, 
but I'm trying to minimize the gap between videos. 

I guess I'll add exception for NX1's case and add 2 secs.

**Comment by KinoSeed** [comment]
@mbriney try v2.75
(it should be adding the 2 sec gap for NX1)

**Comment by mbriney** [comment]
@KinoSeed I installed 2.75 this morning and tried a batch recording for 5 minutes and it created just a single clip.

**Comment by KinoSeed** [comment]
it's not possible.. I just uploaded that version :)

**Comment by mbriney** [comment]
OK let me download and re-install then.
